### ISSUE TITLE
canEdit to click to add marker like imgNotes

### ISSUE THREAD

**Issue by wackyapps** [waynegm/imgViewer2#31]
Hi,

Can I turn imgViewer2 to edit mode and place markers like this: http://waynegm.github.io/imgNotes/wysiwyg_editor.html

I need zoom in, zoom out, pan and drag options that is why I've to only use imgViewer or imgViewer2.
But on the image, I have to allow users to click and add markers (pins) and turn off editing.

Is this possible?

**Comment by waynegm** [comment]
This is relatively easy to do. Just start with the [basic note display example](http://waynegm.github.io/imgViewer2/basic_note.html) and add a custom onClick callback that calls the addNote function if editing is enabled and does nothing otherwise. As written addNote expects  a JSON object with members x, y and note. The x and y values are provided to the onClick event.
